Control component
MeindertKempe/LSD pull request #1
Opened 2024-05-07 15:13 UTC by Stefsk-glitch

2024-05-08 06:20 UTC, GertieMeneer commented
Great cooking

2024-05-08 15:00 UTC, GertieMeneer requested changes

2024-05-08 15:00 UTC, GertieMeneer commented on header/control_component.h
> +#include <iostream>
Don't need this in the header file

2024-05-08 15:00 UTC, GertieMeneer commented on src/ControlComponent.cpp
> +		if (e.key.keysym.sym == SDLK_d) { cout << "Action: move right" << endl; }
Maybe convert this to switch statement, not necessary though

2024-05-08 15:00 UTC, GertieMeneer commented on src/main.cpp
> -}
No empty line at the end of the file

2024-05-16 08:33 UTC, MeindertKempe requested changes

2024-05-16 08:33 UTC, MeindertKempe commented on header/control_component.h
> +#pragma once
Do we use `#pragma once` and no `#ifdef`'s? since `#pragma once` is technically non standard.

2024-05-16 08:33 UTC, MeindertKempe commented on CMakeLists.txt
> +target_sources(lsd PUBLIC ${sources} "${CMAKE_SOURCE_DIR}/dependencies/src/glad.c" "header/control_component.h")
You shouldn't need to add a header file to the sources.

2024-05-16 08:33 UTC, MeindertKempe commented on src/main.cpp
>  void Init(){
Somewhat dubious formatting here.

2024-05-16 09:21 UTC, GertieMeneer approved these changes

2024-05-16 09:55 UTC, MeindertKempe approved these changes

2024-05-16 10:16 UTC, merged